"""Поправил модели

Revision ID: c41e4c0365fc
Revises: 19454f99175f
Create Date: 2024-02-05 14:58:38.215042

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c41e4c0365fc'
down_revision: Union[str, None] = '19454f99175f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_approvers_user_id'), 'approvers', ['user_id'], unique=False)
    op.create_index(op.f('ix_association_table_author_id'), 'association_table', ['author_id'], unique=False)
    op.create_index(op.f('ix_association_table_library_id'), 'association_table', ['library_id'], unique=False)
    op.drop_index('ix_managers_fullname', table_name='managers')
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_index('ix_roles_role', table_name='roles')
    op.create_index(op.f('ix_roles_user_id'), 'roles', ['user_id'], unique=False)
    op.drop_index('ix_users_disabled', table_name='users')
    op.drop_index('ix_users_fullname', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_fullname', 'users', ['fullname'], unique=False)
    op.create_index('ix_users_disabled', 'users', ['disabled'], unique=False)
    op.drop_index(op.f('ix_roles_user_id'), table_name='roles')
    op.create_index('ix_roles_role', 'roles', ['role'], unique=False)
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.create_index('ix_managers_fullname', 'managers', ['fullname'], unique=False)
    op.drop_index(op.f('ix_association_table_library_id'), table_name='association_table')
    op.drop_index(op.f('ix_association_table_author_id'), table_name='association_table')
    op.drop_index(op.f('ix_approvers_user_id'), table_name='approvers')
    # ### end Alembic commands ###
